### ISSUE TITLE
lalavelインストール

### ISSUE THREAD

**Issue by Nadeshiko-miyu** [Nadeshiko-miyu/twisters2023#16]

**Comment by Nadeshiko-miyu** [comment]
Dockerfileをphpの下で書いてcompose up -dとしたら、

failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/php/manifests/7.2-fpm": dial tcp 44.205.64.79:443: i/o timeout　

のエラーが出て撃沈

**Comment by JunichiroNakashima** [comment]
了解、サルベージに向かいます！

**Comment by JunichiroNakashima** [comment]
見に行きました。docker compose up -d は、twisters2023 の直下でやるのみです。
Dockerfile を php の下で書いたら、ルートのdocker-compose.yml の php コンテナの設定欄にその旨を書きます。

で、phpの下で書いたというDockerfile が見当たらない・・・

とりあえず、上記の意味するところをdocker-compose.yml に書き足しました。
他のdbやnginxコンテナも、image: **** ではなく、
build:
      context: ./infra/**コンテナのフォルダ**
      dockerfile: Dockerfile
に書き換えて、Dockerfile を書くことになります。

**Comment by JunichiroNakashima** [comment]
むむ・・・16がpush できない、美柚が書き換えた？
このあたり、同時進行のプロジェクトに慣れておらず・・・
少し今日は立て込んでいるので、直下のdocker-compose.yml を直接下に貼り付けます。

version: "3"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./infra/mysql/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
  
  php:
    build:
      context: ./infra/php
      dockerfile: Dockerfile
    volumes:
      - ./infra/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]

  nginx:
    image: nginx:latest
    volumes:
      - ./infra/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./infra/nginx/html:/usr/share/nginx/html
    restart: always
    ports: ["${APP_PORT_NUMBER}:80"]
    depends_on: ["php"]

**Comment by JunichiroNakashima** [comment]
そして、自分のサイトのphpコンテナのDockerfile 見たけど、
かなり複雑で難しい・・・

**Comment by JunichiroNakashima** [comment]
で、同じ趣旨の解説サイト無いか探していたら、

https://zenn.dev/naoyuki42/articles/ae215286ba92b2

↑これが近いかも！フォルダの名前が、infra ではなく container だけど、
むしろそちらの方が趣旨に近いかも。※containers 複数形がしっくり来るけどね

**Comment by Nadeshiko-miyu** [comment]
この問題は解決できて、compose出来たんだけど、いざexec php bashをすると
bash: composer: command not found
と出てしまう。
お父さんのリンクを参考にして従っているはずだけど...

**Comment by JunichiroNakashima** [comment]
docker-compose exec php bash
でうまくいったよ。
docker-compose up -d の前に、
docker-compose build で image を作り直さきゃだめかも。

**Comment by Nadeshiko-miyu** [comment]
![Screenshot 2023-01-13 232337](https://user-images.githubusercontent.com/109264712/212342401-06d4243a-a0a1-4931-8af5-327768fa24c3.png)
何回かやり直してみたり、パソコン再起動してみたけどやっぱりできない。パソコン自体に何か問題があるのかな

**Comment by JunichiroNakashima** [comment]
見たよ！最初の流儀のところで少し提案というか、ナランハ流に引きずられたところをなでしこ流に変えたいです。
(1)フォルダ名 infra → docker-containers にしたい
(2)フォルダ名 backend → laravel-project にしたい
そして、いま、php のコンテナの /var/www/html が 
(3a)docker-compose.yml の指定により ./backend/htmlと関連し
(3b)Dockerfileの最後の指定により exec php bash で自動で開く
けど、
(3a')phpコンテナの /var/www/laravel-project ⇔ ubuntu の (2)で作った ~/projects/twisters2023/laravel-project
つまり docker-compose.yml の
      - ./backend/html:/var/www/html → ./laravel-project:/var/www/laravel-project
※他も替えるところある      
(3b')phpコンテナのDockerfile WORKDIR /var/www/html → WORKDIR /var/www/laravel-project
※WORKDIR で指定したフォルダは、存在しなければ作ってくれる

以上の仕込みを行った上で、docker compose build でイメージ作り直して
(4a)phpコンテナに入る。(3b')により、laravel-projectフォルダが作られてそこに居るはず。
(4b)composer のインストールができているか確認
`composer --version`
(4c)laravel-project フォルダで laravel をインストール
[ `composer create-project laravel/laravel .`](https://www.google.com/search?client=firefox-b-d&q=%E7%8F%BE%E5%9C%A8%E3%81%AE%E3%83%95%E3%82%A9%E3%83%AB%E3%83%80%E3%81%AB%E3%83%A9%E3%83%A9%E3%83%99%E3%83%AB%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB)

父はうまく行ったよ

**Comment by Nadeshiko-miyu** [comment]
https://getcomposer.org/doc/00-intro.md#installation-windows
ここを参考にDockerfileを書き換えたら上手くいったっぽい。パソコンのスペックがあんまりよくないから、ファイルのサイズが大きすぎたのが原因かもしれないと色々なサイトをめぐって思った。

**Comment by Nadeshiko-miyu** [comment]
とにかく、ララベルインストール成功！ちょっと時間かかったけど良かった
