### ISSUE TITLE
Laravelインストール その2

### ISSUE THREAD

**Issue by JunichiroNakashima** [Nadeshiko-miyu/twisters2023#18]
こちらではインストールできませんでした・・・
本当は、マージの前にコードを精査して対応するのでしょうが、
マージしたので、新しいIssue(Branch)をたてて検討です。

まず、.gitignore に、laravel-project が入っていたので、父のlaravel-project フォルダはスッカラカン。
あと、使わなくなった backend フォルダと infra フォルダ削除。
.env.devlop ← typo(スペルミス) .env.develop に変更、

あと、美柚PCのスペックに関しては別Issue？なでしこ投資案件が勃発です！

**Comment by JunichiroNakashima** [comment]
laravel-project の中でも、環境によって変えるところが出てくるので、
laravel-project 直下にも.env (と.env.devleop)を置く形になります。
ややこしい！

**Comment by JunichiroNakashima** [comment]
あと、.gitignoreに入っていたmysql は、データベースの中身かな？
データベースの中身は、ファイルで管理して.gitignoreで対応するのか・・・
僕の本当に数少ない経験でいうと、データベースの中身はdockerのvolumeにするのが主流という気がします。
※データベースも、migrationとか覚える事多い。美柚のペースは驚異的ですが・・・

**Comment by Nadeshiko-miyu** [comment]
lalavel-projectとmysqlをgitignoreに入れたのは、docker-composerを起動した時点で自動的にインストールされてたやつだから、gitで上げたらdocker-compose upで立ち上げたときにファイルがダブっちゃうかなと思って、追加してみました。
ただその心配が見当違いだったら、gitignoreから外してcommitしておきます。
issueはミユの方で解決したのでmergeしてしまいました(;'∀')

**Comment by Nadeshiko-miyu** [comment]
そして、データベースの中身は 
volumes:
      - ./docker-containers/mysql:/var/lib/mysql
 で既にvolumeをしているはず。

**Comment by JunichiroNakashima** [comment]
？変更反映されていない？issueも残っているし、mergeされた形跡もない？？

そっか、データベースの中身をdocker-containers/mysql フォルダに置くなら、
ここはgitから外しておく必要がありそうだね。
merge するたびに せっかく入力されたDBの中身が飛んじゃうから。

**Comment by JunichiroNakashima** [comment]
あと、miyu がどんどんmergeして良いよ。
イッシュー → ブランチ → プルリク → マージ って一人芝居が続くけど、
みんなそうやっているみたい。

**Comment by Nadeshiko-miyu** [comment]
＞？変更反映されていない？issueも残っているし、mergeされた形跡もない？？
これはlaravel-project＃１のこと！
